### PR TITLE
[#14] Introduce *.Extra modules

### LINKED ISSUE #14: Create `*.Extra` module and not reexport it by default
* `groupBy` functions
* `BoundedEnum`

```haskell
every      :: (Bounded a, Enum a) => [a]  -- all values
cycleSucc  :: (Bounded a, Enum a) => a -> a  -- like succ, but doesn't fail on maxBound
safeToEnum :: Enum a => Int -> Maybe a  -- Nothing if Int outside enum range
```
* `Bifunctor`

```haskell
bimapF  :: (Functor f, Bifunctor p) => (a -> c) -> (b -> d) -> f (p a b) -> f (p c d)
firstF  :: ... similar
secondF :: ... similar
```

### PR DESCRIPTION
**Pull request by ChShersh**
Resolves #14

### CODE REVIEW

File: src/Universum/Extra/Enum.hs [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+
+{- | Returns all values of some 'Bounded' 'Enum' in ascending order.
+
+>>> data TrafficLight = Red | Blue | Green deriving (Show, Enum, Bounded)
+>>> universe :: [TrafficLight]
+[Red,Blue,Green]
+>>> universe :: [Bool]
+[False,True]
+-}
+universe :: (Bounded a, Enum a) => [a]
```
Comment (vrom911) [inline src/Universum/Extra/Enum.hs]: 🌌
